# Generated by Django 3.2.3 on 2021-05-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_bookticket_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerdata',
            name='full_sheet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winnerdata',
            name='half_sheet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winnerdata',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.ticket'),
        ),
    ]
