# Generated by Django 3.2.3 on 2021-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210603_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Admin', 'Admin'), ('SuperUser', 'SuperUser'), ('Developer', 'Developer')], default='Agent', max_length=10),
        ),
    ]
