# Generated by Django 3.2.3 on 2021-06-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_profile_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='products',
            new_name='User_Type',
        ),
    ]
