# Generated by Django 3.2.3 on 2021-06-19 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210612_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspend_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
