# Generated by Django 3.2.3 on 2021-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_suspenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Phone',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
